contract('Safe', async accounts => {
    it('deploy new safe from factory')
    it('deposits some funds')
    it('adds new modules')
    it('removes modules')
    it('can not remove last verification module')
    it('successfully executes transaction')
    it('cannot replay transaction')
    it('refunded caller')
})
