image: node

# Cache modules in between jobs
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

before_script:
    - yarn

stages:
    - build
    - test
    - security
    - deploy

compile:
    stage: build
    script:
        - ./node_modules/.bin/truffle compile

truffle:
    stage: test
    script:
        - ./node_modules/.bin/truffle test

coverage:
    stage: test
    script:
        - yarn add solidity-coverage
        - ./node_modules/.bin/solidity-coverage
    coverage: '/All files[ |]+[0-9.]+[ |]+([0-9.]+)/'
    artifacts:
        paths:
            - coverage

# This could be pushed to a web page?
gas-reporter:
    stage: test
    script:
        - yarn add eth-gas-reporter
        - cp -f truffle-reporter.js truffle.js
        - ./node_modules/.bin/truffle test

linter:
    stage: security
    script:
        - yarn add solium
        - ./node_modules/.bin/solium -d contracts/

# Report, but only for master
pages:
    stage: deploy
    dependencies:
        - coverage
    script:
        - mv coverage public
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master

# And static analysis?
