image: node:alpine

before_script:
    - apk update && apk add --no-cache python alpine-sdk git
    - npm install -g truffle ganache-cli

all_tests:
    script:
        - npm install
        - truffle compile
        - truffle test

# Maybe we could add a linter?
# And static analysis?
# And coverage?
