image: node

# Cache modules in between jobs
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

before_script:
    - npm install

stages:
    - build
    - test
    - security
    - deploy

compile:
    stage: build
    script:
        - npx truffle compile

truffle:
    stage: test
    script:
        - npx truffle test

coverage:
    stage: test
    script:
        - npm install -g truffle
        - npm install solidity-coverage
        - ./node_modules/.bin/solidity-coverage
    coverage: '/All files[ |]+[0-9.]+[ |]+([0-9.]+)/'
    artifacts:
        paths:
            - coverage

# This could be pushed to a web page?
gas-reporter:
    stage: test
    script:
        - npm install eth-gas-reporter
        - cp -f truffle-reporter.js truffle.js
        - npx truffle test

linter:
    stage: security
    script:
        - npm install solium
        - npx solium -d contracts/

# Report, but only for master
coverage-page:
    stage: deploy
    dependencies:
        - coverage
    script:
        - mv coverage public
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master

# And static analysis?
